// Centralized pt-BR UI copy, organized by domain. Component literals live here
// so future copy edits don't require hunting across components. Domain error
// messages and zod validation strings stay in their existing `lib/*/errors.ts`
// and `lib/*/validation.ts` files (already centralized + imported by actions).
//
// Single-language (pt-BR) by design — not a full i18n framework. If a second
// locale is ever needed, mirror this object and add a resolver.

import type { Role } from '@/types'

/** Role labels — confirmed: Gestor / Professor / Representante. */
export const ROLE_LABELS: Record<Role, string> = {
  principal:   'Gestor',
  teacher:     'Professor',
  student_rep: 'Representante',
}

export const t = {
  nav: {
    dashboard:     'Painel',
    calendar:      'Calendário',
    courts:        'Quadras',
    collaborators: 'Colaboradores',
  },

  common: {
    cancel:       'Cancelar',
    save:         'Salvar',
    saveChanges:  'Salvar alterações',
    saving:       'Salvando…',
    delete:       'Excluir',
    remove:       'Remover',
    removing:     'Removendo...',
    close:        'Fechar',
    keep:         'Manter',
    edit:         'Editar',
    add:          'Adicionar',
    switch:       'Trocar',
    active:       'Ativo',
    pending:      'Pendente',
    optional:     '(opcional)',
    email:        'Email',
    password:     'Senha',
    fullName:     'Nome completo',
    role:         'Função',
    emailPlaceholder:    'voce@exemplo.com',
    fullNamePlaceholder: 'João da Silva',
  },

  header: {
    dashboard: {
      title: 'Painel',
    },
    calendar: {
      title:       'Calendário',
      description: 'Visão semanal das reservas de quadras',
    },
    collaborators: {
      title:       'Colaboradores',
      description: 'Pessoas com acesso à sua escola',
    },
    settings: {
      title:       'Configurações',
      description: 'Gerencie as preferências da sua conta',
    },
  },

  auth: {
    login: {
      title:      'Bem-vindo de volta',
      subtitle:   'Insira suas credenciais para acessar sua conta',
      signIn:     'Entrar',
      signingIn:  'Entrando...',
      orContinue: 'Ou continue com',
      noAccount:  'Não tem uma conta?',
      signUp:     'Criar conta',
      hero:       'Agendamento de quadras para escolas.',
    },
    register: {
      title:         'Crie sua conta',
      subtitle:      'Você vai entrar ou criar sua escola no próximo passo',
      createAccount: 'Criar conta',
      creating:      'Criando conta...',
      orContinue:    'Ou continue com',
      haveAccount:   'Já tem uma conta?',
      signIn:        'Entrar',
    },
    onboarding: {
      title:           'Crie sua organização',
      subtitle:        (email: string) =>
        `Você está conectado como ${email}. Configure sua escola para começar.`,
      schoolName:      'Nome da escola',
      schoolPlaceholder: 'Colégio Dom Pedro',
      principalNote:   'Você será o gestor da escola. Um identificador de organização é gerado para você — encontre-o depois nas Configurações.',
      createSchool:    'Criar escola',
      creating:        'Criando escola...',
      wrongAccount:    'Conta errada?',
      signOut:         'Sair',
    },
    welcome: {
      title:        'Você foi convidado',
      subtitle:     'Aceite seu convite para entrar em',
      yourSchool:   'sua escola',
      setPassword:  'Defina uma senha',
      join:         (school: string) => `Entrar em ${school}`,
      joining:      'Entrando...',
    },
    google: {
      continue:    'Continuar com Google',
      redirecting: 'Redirecionando…',
      startError:  'Não foi possível iniciar o login com o Google. Tente novamente.',
    },
  },

  dashboard: {
    stats: {
      onCourtNow:        'Em quadra agora',
      live:              'Ao vivo',
      noSession:         'Sem sessão',
      noActiveSession:   'Nenhuma sessão ativa no momento',
      minRemaining:      (min: number) => `${min} min restantes`,
      todaysBookings:    'Reservas de hoje',
      bookingSingular:   'reserva',
      bookingPlural:     'reservas',
      bookingsToday:     (n: number) => (n === 1 ? 'reserva hoje' : 'reservas hoje'),
      last7DaysVs:       'Últimos 7 dias · vs',
      yesterday:         'ontem',
      noBookingsToday:   'Nenhuma reserva hoje ainda',
      availableSlots:    'Horários disponíveis',
      busy:              'Cheio',
      open:              'Livre',
      available:         (capacity: number) => `/ ${capacity} disponíveis`,
      occupancyToday:    (pct: number) => `${pct}% de ocupação hoje`,
      noCourtData:       'Nenhum dado de quadra disponível',
    },
    upcoming: {
      title:        'Próximas de hoje',
      noneLeft:     'Nenhuma reserva restante hoje',
      noneLeftHint: 'Novas reservas para hoje aparecerão aqui.',
      noBookings:   'Sem reservas ainda',
      bookingCount: (n: number) => `${n} ${n === 1 ? 'reserva' : 'reservas'}`,
      startsIn:     (label: string) => `em ${label}`,
      timeLeft:     (label: string) => `${label} restante`,
    },
    weekly: {
      title:       'Uso semanal das quadras',
      range:       'Seg – Dom',
      seriesLabel: 'Reservas',
      empty:       'Nenhum dado de reserva ainda',
      emptyHint:   'O uso das quadras aparecerá aqui assim que houver reservas.',
      weekdays:    ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
    },
  },

  calendar: {
    description: 'Visão semanal das reservas de quadras',
    today:       'Hoje',
    previous:    'Anterior',
    next:        'Próximo',
    legendYou:   'Você',
    legendOthers:'Outros',
    views: {
      month:  'Mês',
      week:   'Semana',
      day:    'Dia',
      agenda: 'Agenda',
    },
    // react-big-calendar internal labels (agenda table + empty range).
    messages: {
      date:           'Data',
      time:           'Horário',
      event:          'Evento',
      allDay:         'Dia inteiro',
      week:           'Semana',
      work_week:      'Semana útil',
      day:            'Dia',
      month:          'Mês',
      previous:       'Anterior',
      next:           'Próximo',
      yesterday:      'Ontem',
      tomorrow:       'Amanhã',
      today:          'Hoje',
      agenda:         'Agenda',
      noEventsInRange:'Não há reservas neste período.',
      showMore:       (total: number) => `+${total} mais`,
    },
  },

  collaborators: {
    invite:        'Convidar colaborador',
    emptyTitle:    'Nenhum colaborador ainda',
    emptyDesc:     'Convide membros da equipe para gerenciar quem tem acesso à sua escola.',
    searchPlaceholder: 'Buscar por nome ou email',
    noMatches:     'Nenhum resultado',
    noMatchesDesc: (q: string) => `Nenhum colaborador corresponde a "${q}".`,
    table: {
      name:    'Nome',
      email:   'Email',
      role:    'Função',
      status:  'Status',
      actions: 'Ações',
      inUse:   'Em uso',
    },
    dialog: {
      title:       'Convidar colaborador',
      description: 'Um link de convite será enviado ao email da pessoa. Você define a função — ela não pode alterá-la.',
      emailLabel:  'Email',
      emailPlaceholder: 'professor@escola.edu',
      roleLabel:   'Função',
      rolePlaceholder: 'Selecione uma função',
      roleTeacher:    'Professor',
      roleStudentRep: 'Representante',
      cancel:      'Cancelar',
      send:        'Enviar convite',
      sending:     'Enviando...',
      sentTitle:   'Convite enviado',
      sentDesc:    (email: string) => `Um link de convite foi enviado para ${email}.`,
      sendError:   'Não foi possível enviar o convite. Tente novamente.',
    },
    actions: {
      removeConfirmTitle: (name: string) => `Remover ${name}?`,
      removeConfirmDesc:  'A pessoa perderá o acesso a esta escola. Isso não afeta as outras escolas das quais ela participa.',
      removed:            (name: string) => `${name} removido`,
      revoked:            'Convite cancelado',
      resentTitle:        'Convite reenviado',
      resentDesc:         (email: string) => `Um novo link de convite foi enviado para ${email}.`,
      removeAria:         (name: string) => `Remover ${name}`,
      cancelInviteAria:   (email: string) => `Cancelar convite de ${email}`,
      resendInviteAria:   (email: string) => `Reenviar convite de ${email}`,
    },
  },

  settings: {
    sections: {
      profile:       'Perfil',
      institutions:  'Instituições',
      authorization: 'Autorização',
      courts:        'Quadras',
      notifications: 'Notificações',
      appearance:    'Aparência',
    },
    profile: {
      title:           'Perfil',
      description:     'Gerencie suas informações pessoais',
      photo:           'Foto de perfil',
      photoGoogle:     'Gerenciada pela sua conta Google.',
      uploading:       'Enviando…',
      changePhoto:     'Trocar foto',
      uploadPhoto:     'Enviar foto',
      removePhoto:     'Remover',
      photoHint:       'JPG, PNG ou GIF. Máx. 2 MB.',
      fullName:        'Nome completo',
      email:           'Email',
      newPassword:     'Nova senha',
      passwordKeep:    'Deixe em branco para manter a atual',
      save:            'Salvar alterações',
      saving:          'Salvando…',
      chooseImage:     'Escolha um arquivo de imagem.',
      imageTooLarge:   'A imagem deve ter menos de 2 MB.',
      photoUpdated:    'Foto de perfil atualizada!',
      photoUploadError:'Não foi possível enviar a foto',
      photoRemoved:    'Foto de perfil removida.',
      photoRemoveError:'Não foi possível remover a foto',
      unexpectedError: 'Ocorreu um erro inesperado.',
      noSession:       'Nenhuma sessão autenticada encontrada',
      profileUpdated:  'Perfil atualizado com sucesso!',
      saveError:       'Não foi possível salvar suas alterações',
      fullNameRequired:'O nome completo é obrigatório',
      emailInvalid:    'Endereço de email inválido',
    },
    institutions: {
      title:       'Instituições',
      description: 'Escolas das quais você participa. Clique em uma escola para torná-la ativa.',
      none:        'Você ainda não participa de nenhuma escola.',
      switch:      'Trocar',
      active:      'Ativo',
    },
    authorization: {
      title:        'Identificador da organização',
      description:  'O identificador único da sua escola',
      accessToken:  'Token de acesso',
      copyAria:     'Copiar token',
      copied:       'Copiado para a área de transferência',
      alertTitle:   'Reservado para uso futuro',
      alertDesc:    'Este identificador é gerado quando você cria uma escola. Ele não é usado para login nem controle de acesso.',
    },
    notifications: {
      title:           'Notificações',
      description:     'Escolha quais atualizações você recebe por email',
      newBooking:      'Email em nova reserva',
      newBookingDesc:  'Receba um email quando uma nova reserva for criada',
      bookingChanges:  'Email em alterações de reserva',
      bookingChangesDesc: 'Receba um email quando uma reserva for atualizada ou cancelada',
    },
    appearance: {
      title:       'Aparência',
      description: 'Escolha como o OpenCourt aparece no seu dispositivo',
      themeAria:   'Tema',
      light:       'Claro',
      dark:        'Escuro',
      system:      'Sistema',
    },
  },

  courts: {
    title:        'Quadras',
    description:  'Gerencie as quadras disponíveis para reserva',
    newNamePlaceholder: 'Nome da nova quadra',
    add:          'Adicionar quadra',
    emptyTitle:   'Nenhuma quadra ainda',
    emptyDesc:    'Adicione a primeira quadra para que os membros possam começar a reservar.',
    noBookings:   'Sem reservas ainda',
    bookingCount: (n: number) => `${n} ${n === 1 ? 'reserva' : 'reservas'}`,
    inUse:        'Em uso',
    rename:       'Renomear',
    save:         'Salvar',
    renameAria:   (name: string) => `Renomear ${name}`,
    cancelRename: 'Cancelar renomeação',
    deleteAria:   (name: string) => `Excluir ${name}`,
    deleteTitle:  (name: string) => `Excluir ${name}?`,
    deleteBlocked:(n: number) => `Esta quadra tem ${n} ${n === 1 ? 'reserva' : 'reservas'} e não pode ser excluída até que sejam removidas.`,
    deleteConfirm:'Isso remove a quadra do formulário de reserva e do calendário. Esta ação não pode ser desfeita.',
    deleteAction: 'Excluir quadra',
    added:        'Quadra adicionada',
    renamed:      'Quadra renomeada',
    removed:      'Quadra removida',
    firstGate: {
      title:    'Adicione sua primeira quadra',
      desc:     'Antes que sua escola possa receber reservas, cadastre a primeira quadra. Você pode adicionar mais ou renomeá-las quando quiser em Configurações → Quadras.',
      nameLabel:'Nome da quadra',
      namePlaceholder: 'ex.: Quadra Central',
      submit:   'Adicionar quadra e continuar',
      submitting: 'Adicionando…',
      addedTitle: 'Quadra adicionada',
      addedDesc:  'Sua escola está pronta para reservas.',
    },
  },

  booking: {
    cta:           'Nova reserva',
    newTitle:      'Nova reserva',
    newDescription:'Reserve uma quadra para uma sessão. Escolha a quadra, o dia e o horário.',
    titleLabel:    'Título',
    titlePlaceholder: 'Fundamentos de basquete',
    courtLabel:    'Quadra',
    selectCourt:   'Selecione uma quadra',
    noCourts:      'Nenhuma quadra disponível',
    dateLabel:     'Data',
    startLabel:    'Início',
    endLabel:      'Fim',
    notesLabel:    'Observações',
    notesPlaceholder: 'Algo que a equipe deva saber…',
    cancel:        'Cancelar',
    create:        'Criar reserva',
    createdTitle:  'Reserva criada',
    editTitle:     'Editar reserva',
    detailsTitle:  'Detalhes da reserva',
    editDescription:'Atualize o título, a quadra, o dia ou o horário desta sessão.',
    detailsDescription: (by: string) => `Reservado por ${by}. Você só pode alterar suas próprias reservas.`,
    anotherMember: 'outro membro',
    deletePrompt:  'Excluir esta reserva?',
    keep:          'Manter',
    delete:        'Excluir',
    save:          'Salvar alterações',
    close:         'Fechar',
    updated:       'Reserva atualizada',
    deleted:       'Reserva excluída',
  },

  account: {
    settings: 'Configurações',
    logOut:   'Sair',
  },

  schoolSwitcher: {
    organizations:      'Organizações',
    createOrganization: 'Criar organização',
  },
} as const
